from django.db import models
from users.models import User

# Create your models here.

class Restraunt(models.Model):
    name = models.CharField("이름", max_length=30)
    address = models.CharField("주소", max_length=30)
    address_gu = models.CharField("구", max_length=5)
    mon_start = models.CharField("월요일 개장 시간", max_length=20, null=True)
    mon_end = models.TimeField("월요일 종료 시간", auto_now=False, null=True)
    mon_break_start = models.TimeField("월요일 휴식 시작", auto_now=False, null=True)
    mon_break_end = models.TimeField("월요일 휴식 종료", auto_now=False, null=True)
    mon_last_order = models.CharField("월요일 주문 마감", max_length=20, null=True)
    tue_start = models.CharField("화요일 개장 시간", max_length=20, null=True)
    tue_end = models.TimeField("화요일 종료 시간", auto_now=False, null=True)
    tue_break_start = models.TimeField("화요일 휴식 시작", auto_now=False, null=True)
    tue_break_end = models.TimeField("화요일 휴식 종료", auto_now=False, null=True)
    tue_last_order = models.CharField("화요일 주문 마감", max_length=20, null=True)
    wed_start = models.CharField("수요일 개장 시간", max_length=20, null=True)
    wed_end = models.TimeField("수요일 종료 시간", auto_now=False, null=True)
    wed_break_start = models.TimeField("수요일 휴식 시작", auto_now=False, null=True)
    wed_break_end = models.TimeField("수요일 휴식 종료", auto_now=False, null=True)
    wed_last_order = models.CharField("수요일 주문 마감", max_length=20, null=True)
    thu_start = models.CharField("목요일 개장 시간", max_length=20, null=True)
    thu_end = models.TimeField("목요일 종료 시간", auto_now=False, null=True)
    thu_break_start = models.TimeField("목요일 휴식 시작", auto_now=False, null=True)
    thu_break_end = models.TimeField("목요일 휴식 종료", auto_now=False, null=True)
    thu_last_order = models.CharField("목요일 주문 마감", max_length=20, null=True)
    fri_start = models.CharField("금요일 개장 시간", max_length=20, null=True)
    fri_end = models.TimeField("금요일 종료 시간", auto_now=False, null=True)
    fri_break_start = models.TimeField("금요일 휴식 시작", auto_now=False, null=True)
    fri_break_end = models.TimeField("금요일 휴식 종료", auto_now=False, null=True)
    fri_last_order = models.CharField("금요일 주문 마감", max_length=20, null=True)
    sat_start = models.CharField("토요일 개장 시간", max_length=20, null=True)
    sat_end = models.TimeField("토요일 종료 시간", auto_now=False, null=True)
    sat_break_start = models.TimeField("토요일 휴식 시작", auto_now=False, null=True)
    sat_break_end = models.TimeField("토요일 휴식 종료", auto_now=False, null=True)
    sat_last_order = models.CharField("토요일 주문 마감", max_length=20, null=True)
    sun_start = models.CharField("일요일 개장 시간", max_length=20, null=True)
    sun_end = models.TimeField("일요일 종료 시간", auto_now=False, null=True)
    sun_break_start = models.TimeField("일요일 휴식 시작", auto_now=False, null=True)
    sun_break_end = models.TimeField("일요일 휴식 종료", auto_now=False, null=True)
    sun_last_order = models.CharField("일요일 주문 마감", max_length=20, null=True)
    phone_no = models.CharField("연락처", max_length=15)
    parking = models.BooleanField("주차시설", default=False)
    rating = models.FloatField("평점")
    rating_count = models.IntegerField("평점 수")
    image = models.ImageField("대표 이미지", upload_to=None)

class RestrauntMenu(models.Model):
    restraunt_pk = models.ForeignKey(Restraunt, verbose_name="음식점 id", on_delete=models.CASCADE)
    name = models.CharField("이름", max_length=30)
    price = models.IntegerField("가격")

class RestrauntReview(models.Model):
    restraunt_pk = models.ForeignKey(Restraunt, verbose_name="음식점 id", on_delete=models.CASCADE)
    user_pk = models.ForeignKey(User, verbose_name="유저 id", on_delete=models.CASCADE)
    comment = models.TextField("내용")
