# Generated by Django 4.1 on 2024-02-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True, verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=None, verbose_name="프로필 이미지"
            ),
        ),
    ]
