# Generated by Django 4.1 on 2024-02-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restraunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("address", models.CharField(max_length=30, verbose_name="주소")),
                ("address_gu", models.CharField(max_length=5, verbose_name="구")),
                (
                    "mon_busi_time",
                    models.CharField(max_length=20, verbose_name="월요일 영업시간"),
                ),
                (
                    "mon_break_time",
                    models.CharField(max_length=20, verbose_name="월요일 휴식시간"),
                ),
                ("mon_finish_time", models.TimeField(verbose_name="월요일 마감시간")),
                (
                    "tue_busi_time",
                    models.CharField(max_length=20, verbose_name="화요일 영업시간"),
                ),
                (
                    "tue_break_time",
                    models.CharField(max_length=20, verbose_name="화요일 휴식시간"),
                ),
                ("tue_finish_time", models.TimeField(verbose_name="화요일 마감시간")),
                (
                    "wed_busi_time",
                    models.CharField(max_length=20, verbose_name="수요일 영업시간"),
                ),
                (
                    "wed_break_time",
                    models.CharField(max_length=20, verbose_name="수요일 휴식시간"),
                ),
                ("wed_finish_time", models.TimeField(verbose_name="수요일 마감시간")),
                (
                    "thu_busi_time",
                    models.CharField(max_length=20, verbose_name="목요일 영업시간"),
                ),
                (
                    "thu_break_time",
                    models.CharField(max_length=20, verbose_name="목요일 휴식시간"),
                ),
                ("thu_finish_time", models.TimeField(verbose_name="목요일 마감시간")),
                (
                    "fri_busi_time",
                    models.CharField(max_length=20, verbose_name="금요일 영업시간"),
                ),
                (
                    "fri_break_time",
                    models.CharField(max_length=20, verbose_name="금요일 휴식시간"),
                ),
                ("fri_finish_time", models.TimeField(verbose_name="금요일 마감시간")),
                (
                    "sat_busi_time",
                    models.CharField(max_length=20, verbose_name="토요일 영업시간"),
                ),
                (
                    "sat_break_time",
                    models.CharField(max_length=20, verbose_name="토요일 휴식시간"),
                ),
                ("sat_finish_time", models.TimeField(verbose_name="토요일 마감시간")),
                (
                    "sun_busi_time",
                    models.CharField(max_length=20, verbose_name="일요일 영업시간"),
                ),
                (
                    "sun_break_time",
                    models.CharField(max_length=20, verbose_name="일요일 휴식시간"),
                ),
                ("sun_finish_time", models.TimeField(verbose_name="일요일 마감시간")),
                ("phone_no", models.CharField(max_length=15, verbose_name="연락처")),
                ("parking", models.BooleanField(default=False, verbose_name="주차시설")),
                ("rating", models.FloatField(verbose_name="평점")),
                ("rating_count", models.IntegerField(verbose_name="평점 수")),
                ("image", models.ImageField(upload_to=None, verbose_name="대표 이미지")),
            ],
        ),
        migrations.CreateModel(
            name="RestrauntMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("price", models.IntegerField(verbose_name="가격")),
            ],
        ),
        migrations.CreateModel(
            name="RestrauntReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="내용")),
                (
                    "restraunt_pk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="single_pages.restraunt",
                        verbose_name="음식점 id",
                    ),
                ),
            ],
        ),
    ]
