# Generated by Django 4.1 on 2024-02-14 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("single_pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restrauntreview",
            name="user_pk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저 id",
            ),
        ),
        migrations.AddField(
            model_name="restrauntmenu",
            name="restraunt_pk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="single_pages.restraunt",
                verbose_name="음식점 id",
            ),
        ),
    ]
