# Generated by Django 4.1 on 2024-02-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restraunt",
            name="fri_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="fri_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="fri_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="mon_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="mon_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="mon_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sat_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sat_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sat_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sun_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sun_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="sun_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="thu_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="thu_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="thu_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="tue_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="tue_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="tue_finish_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="wed_break_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="wed_busi_time",
        ),
        migrations.RemoveField(
            model_name="restraunt",
            name="wed_finish_time",
        ),
        migrations.AddField(
            model_name="restraunt",
            name="fri_break_end",
            field=models.TimeField(null=True, verbose_name="금요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="fri_break_start",
            field=models.TimeField(null=True, verbose_name="금요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="fri_end",
            field=models.TimeField(null=True, verbose_name="금요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="fri_last_order",
            field=models.TimeField(null=True, verbose_name="금요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="fri_start",
            field=models.TimeField(null=True, verbose_name="금요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="mon_break_end",
            field=models.TimeField(null=True, verbose_name="월요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="mon_break_start",
            field=models.TimeField(null=True, verbose_name="월요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="mon_end",
            field=models.TimeField(null=True, verbose_name="월요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="mon_last_order",
            field=models.TimeField(null=True, verbose_name="월요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="mon_start",
            field=models.TimeField(null=True, verbose_name="월요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sat_break_end",
            field=models.TimeField(null=True, verbose_name="토요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sat_break_start",
            field=models.TimeField(null=True, verbose_name="토요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sat_end",
            field=models.TimeField(null=True, verbose_name="토요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sat_last_order",
            field=models.TimeField(null=True, verbose_name="토요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sat_start",
            field=models.TimeField(null=True, verbose_name="토요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sun_break_end",
            field=models.TimeField(null=True, verbose_name="일요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sun_break_start",
            field=models.TimeField(null=True, verbose_name="일요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sun_end",
            field=models.TimeField(null=True, verbose_name="일요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sun_last_order",
            field=models.TimeField(null=True, verbose_name="일요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="sun_start",
            field=models.TimeField(null=True, verbose_name="일요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="thu_break_end",
            field=models.TimeField(null=True, verbose_name="목요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="thu_break_start",
            field=models.TimeField(null=True, verbose_name="목요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="thu_end",
            field=models.TimeField(null=True, verbose_name="목요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="thu_last_order",
            field=models.TimeField(null=True, verbose_name="목요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="thu_start",
            field=models.TimeField(null=True, verbose_name="목요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="tue_break_end",
            field=models.TimeField(null=True, verbose_name="화요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="tue_break_start",
            field=models.TimeField(null=True, verbose_name="화요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="tue_end",
            field=models.TimeField(null=True, verbose_name="화요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="tue_last_order",
            field=models.TimeField(null=True, verbose_name="화요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="tue_start",
            field=models.TimeField(null=True, verbose_name="화요일 개장 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="wed_break_end",
            field=models.TimeField(null=True, verbose_name="수요일 휴식 종료"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="wed_break_start",
            field=models.TimeField(null=True, verbose_name="수요일 휴식 시작"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="wed_end",
            field=models.TimeField(null=True, verbose_name="수요일 종료 시간"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="wed_last_order",
            field=models.TimeField(null=True, verbose_name="수요일 주문 마감"),
        ),
        migrations.AddField(
            model_name="restraunt",
            name="wed_start",
            field=models.TimeField(null=True, verbose_name="수요일 개장 시간"),
        ),
    ]
