# Generated by Django 5.0.2 on 2024-02-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0003_remove_restraunt_fri_break_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restraunt",
            name="fri_start",
            field=models.CharField(max_length=20, null=True, verbose_name="금요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="mon_start",
            field=models.CharField(max_length=20, null=True, verbose_name="월요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sat_start",
            field=models.CharField(max_length=20, null=True, verbose_name="토요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sun_start",
            field=models.CharField(max_length=20, null=True, verbose_name="일요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="thu_start",
            field=models.CharField(max_length=20, null=True, verbose_name="목요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="tue_start",
            field=models.CharField(max_length=20, null=True, verbose_name="화요일 개장 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="wed_start",
            field=models.CharField(max_length=20, null=True, verbose_name="수요일 개장 시간"),
        ),
    ]
