# Generated by Django 4.1 on 2024-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0005_alter_restraunt_fri_last_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restraunt",
            name="url",
            field=models.TextField(
                default="https://www.diningcode.com/", verbose_name="사이트 URL"
            ),
        ),
    ]
