# Generated by Django 4.1 on 2024-02-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0006_restraunt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restraunt",
            name="fri_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="금요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="fri_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="금요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="fri_end",
            field=models.CharField(max_length=20, null=True, verbose_name="금요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="mon_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="월요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="mon_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="월요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="mon_end",
            field=models.CharField(max_length=20, null=True, verbose_name="월요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sat_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="토요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sat_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="토요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sat_end",
            field=models.CharField(max_length=20, null=True, verbose_name="토요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sun_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="일요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sun_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="일요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="sun_end",
            field=models.CharField(max_length=20, null=True, verbose_name="일요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="thu_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="목요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="thu_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="목요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="thu_end",
            field=models.CharField(max_length=20, null=True, verbose_name="목요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="tue_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="화요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="tue_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="화요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="tue_end",
            field=models.CharField(max_length=20, null=True, verbose_name="화요일 종료 시간"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="wed_break_end",
            field=models.CharField(max_length=20, null=True, verbose_name="수요일 휴식 종료"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="wed_break_start",
            field=models.CharField(max_length=20, null=True, verbose_name="수요일 휴식 시작"),
        ),
        migrations.AlterField(
            model_name="restraunt",
            name="wed_end",
            field=models.CharField(max_length=20, null=True, verbose_name="수요일 종료 시간"),
        ),
    ]
